### ISSUE TITLE
Not working against a compose.io instance

### ISSUE THREAD

**Issue by sagivf** [wayann/logstash-input-rethinker#2]
Any idea what `exception=>#<URI::InvalidComponentError: bad component(expected userinfo component or user component): sagiv@invisionapp.com` means? Is this an issue with the connection settings or with the installation?

````
$ ./logstash-5.2.2/bin/logstash -f logstash.conf
Sending Logstash's logs to /Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logs which is now configured via log4j2.properties
[2017-03-23T18:52:44,738][INFO ][logstash.inputs.rethinker] Using version 0.1.x input plugin 'rethinker'. This plugin isn't well supported by the community and likely has no maintainer.
[2017-03-23T18:52:45,147][ERROR][logstash.pipeline        ] Error registering plugin {:plugin=>"#<LogStash::OutputDelegator:0x7ac6f100 @namespaced_metric=#<LogStash::Instrument::NamespacedMetric:0x1f71c853 @metric=#<LogStash::Instrument::Metric:0x7a8dea08 @collector=#<LogStash::Instrument::Collector:0x7b5406ff @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x3657a664 @store=#<Concurrent::Map:0x27f5d3ad @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x32bda0f1>, @fast_lookup=#<Concurrent::Map:0x69852ba7 @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"5e95ba05632faa53681ed471ac6db5910a94be10-22\"]>, @metric=#<LogStash::Instrument::NamespacedMetric:0x6b0b1b3e @metric=#<LogStash::Instrument::Metric:0x7a8dea08 @collector=#<LogStash::Instrument::Collector:0x7b5406ff @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x3657a664 @store=#<Concurrent::Map:0x27f5d3ad @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x32bda0f1>, @fast_lookup=#<Concurrent::Map:0x69852ba7 @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs]>, @logger=#<LogStash::Logging::Logger:0x74f649af @logger=#<Java::OrgApacheLoggingLog4jCore::Logger:0x660b55d3>>, @strategy=#<LogStash::OutputDelegatorStrategies::Shared:0x73ea53ec @output=<LogStash::Outputs::ElasticSearch action=>\"index\", codec=><LogStash::Codecs::JSONLines id=>\"json_lines_2590b6d1-4778-46b3-a72a-e3cdb6c48ab2\", enable_metric=>true, charset=>\"UTF-8\", delimiter=>\"\\n\">, index=>\"muzli\", document_type=>\"feed\", doc_as_upsert=>true, document_id=>\"%{id}\", user=>\"sagiv@invisionapp.com\", password=><password>, hosts=>[https://porqtal1223-23.muzli-elastic-search-v5.invisionapp-israel.composedb.com:17293, https://portal2010-21.muzli-elastic-search-v5.invisionapp-israel.composedb.com:17293], id=>\"5e95ba05632faa53681ed471ac6db5910a94be10-22\", enable_metric=>true, workers=>1, manage_template=>true, template_name=>\"logstash\", template_overwrite=>false, idle_flush_time=>1, script_type=>\"inline\", script_lang=>\"painless\", script_var_name=>\"event\", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, healthcheck_path=>\"/\", absolute_healthcheck_path=>false, resurrect_delay=>5, validate_after_inactivity=>10000, ssl=>true>>, @id=\"5e95ba05632faa53681ed471ac6db5910a94be10-22\", @metric_events=#<LogStash::Instrument::NamespacedMetric:0x336023a3 @metric=#<LogStash::Instrument::Metric:0x7a8dea08 @collector=#<LogStash::Instrument::Collector:0x7b5406ff @agent=nil, @metric_store=#<LogStash::Instrument::MetricStore:0x3657a664 @store=#<Concurrent::Map:0x27f5d3ad @default_proc=nil>, @structured_lookup_mutex=#<Mutex:0x32bda0f1>, @fast_lookup=#<Concurrent::Map:0x69852ba7 @default_proc=nil>>>>, @namespace_name=[:stats, :pipelines, :main, :plugins, :outputs, :\"5e95ba05632faa53681ed471ac6db5910a94be10-22\", :events]>, @output_class=LogStash::Outputs::ElasticSearch>", :error=>"bad component(expected userinfo component or user component): sagiv@invisionapp.com"}
[2017-03-23T18:52:45,153][ERROR][logstash.agent           ] Pipeline aborted due to error {:exception=>#<URI::InvalidComponentError: bad component(expected userinfo component or user component): sagiv@invisionapp.com>, :backtrace=>["/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/jruby/lib/ruby/1.9/uri/generic.rb:412:in `check_user'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/jruby/lib/ruby/1.9/uri/generic.rb:483:in `user='", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:272:in `host_to_url'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:260:in `build_pool'", "org/jruby/RubyArray.java:2414:in `map'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:260:in `build_pool'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client.rb:58:in `initialize'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/http_client_builder.rb:80:in `build'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch.rb:207:in `build_client'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/vendor/bundle/jruby/1.9/gems/logstash-output-elasticsearch-6.2.6-java/lib/logstash/outputs/elasticsearch/common.rb:20:in `register'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/output_delegator_strategies/shared.rb:8:in `register'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/output_delegator.rb:37:in `register'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:282:in `register_plugin'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:293:in `register_plugins'", "org/jruby/RubyArray.java:1613:in `each'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:293:in `register_plugins'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:302:in `start_workers'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/pipeline.rb:232:in `run'", "/Users/sagivf/dev/muzli/muzli-logstash-v2/logstash-5.2.2/logstash-core/lib/logstash/agent.rb:387:in `start_pipeline'"]}
[2017-03-23T18:52:45,202][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
^C[2017-03-23T18:52:48,012][WARN ][logstash.runner          ] SIGINT received. Shutting down the agent.
[2017-03-23T18:52:48,020][WARN ][logstash.agent           ] stopping pipeline {:id=>"main"}
```

**Comment by wayann** [comment]
could you make a reproducible test?
logstash errors aren't developer friendly at all....

**Comment by sagivf** [comment]
ok, so I was able to solve this.
Apparently unlike version 2.x you can't use "@" in the user property...
